// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozzpwprysuikwwesyjsi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96enB3cHJ5c3Vpa3d3ZXN5anNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODk1MTIsImV4cCI6MjA3MjY2NTUxMn0.oN2Cndw9f4imyaJ0g3nZALe_xjv42UyclamKL8c_i7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});